base/urls.py
from django.urls import path

from base.views import (
    EncounterDetailView,
    MainView,
    NPCDetailView,
    NPCFormView,
    NPCListView,
    NPCPowerDetailView,
    PCPartyView,
    PowerCreateFromImage,
)

urlpatterns = [
    path('npc/create/', NPCFormView.as_view(), name='npc_create'),
    path('npc/list/', NPCListView.as_view(), name='npc_list'),
    path('npc/detail/<pk>', NPCDetailView.as_view(), name='npc'),
    path(
        'npc/detail/<pk>/power/<power_pk>',
        NPCPowerDetailView.as_view(),
        name='npc_power',
    ),
    path('encounter/detail/<pk>', EncounterDetailView.as_view(), name='encounter'),
    path(
        'power/create/from-image',
        PowerCreateFromImage.as_view(),
        name='power_from_image',
    ),
    path('party/detail/<pk>', PCPartyView.as_view(), name='party'),
    path('', MainView.as_view(), name='main_view'),
]

dnd_helper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('favicon.ico', favicon_view),
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('generator/', include('generator.urls')),
    path('printer/', include('printer.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # type: ignore

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

base/models.py
from collections import Counter

from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField

from base.constants import (
    ArmorTypeEnum,
    AttributesEnum,
    NPCClass,
    NPCRace,
    ShieldTypeEnum,
    SizeEnum,
    SkillsEnum,
    VisionEnum,
)


class Race(models.Model):
    class Meta:
        verbose_name = 'Раса'
        verbose_name_plural = 'Расы'

    name = models.CharField(
        verbose_name='Название',
        max_length=NPCRace.max_length(),
        choices=NPCRace.generate_choices(),
        unique=True,
    )
    speed = models.PositiveSmallIntegerField(default=6, verbose_name='Скорость')
    const_bonus_attrs = MultiSelectField(
        verbose_name='Обязательные бонусы характеристик',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    var_bonus_attrs = MultiSelectField(
        verbose_name='Выборочные бонусы характеристик',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        null=True,
        blank=True,
    )
    size = models.CharField(
        verbose_name='Размер',
        max_length=SizeEnum.max_length(),
        choices=SizeEnum.generate_choices(is_sorted=False),
        default=SizeEnum.AVERAGE.name,
    )
    vision = models.CharField(
        verbose_name='Зрение',
        max_length=VisionEnum.max_length(),
        choices=VisionEnum.generate_choices(),
        default=VisionEnum.TWILIGHT.name,
    )

    fortitude_bonus = models.SmallIntegerField(
        verbose_name='Бонус стойкости', default=0
    )
    reflex_bonus = models.SmallIntegerField(verbose_name='Бонус реакции', default=0)
    will_bonus = models.SmallIntegerField(verbose_name='Бонус воли', default=0)

    skill_bonuses = MultiSelectField(
        verbose_name='Бонусы навыков',
        choices=SkillsEnum.generate_choices(),
        max_choices=2,
        null=True,
        blank=True,
    )

    def __str__(self):
        return NPCRace[self.name].value

    @property
    def test(self):
        return self.get_name_display()


class RaceBonus(models.Model):
    bonus = models.TextField()
    race = models.ForeignKey(Race, on_delete=models.CASCADE)


class Class(models.Model):
    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'

    name = models.CharField(
        verbose_name='Название',
        max_length=NPCClass.max_length(),
        choices=NPCClass.generate_choices(),
        unique=True,
    )
    fortitude_bonus = models.SmallIntegerField(
        verbose_name='Бонус стойкости', default=0
    )
    reflex_bonus = models.SmallIntegerField(verbose_name='Бонус реакции', default=0)
    will_bonus = models.SmallIntegerField(verbose_name='Бонус воли', default=0)
    trained_skills = MultiSelectField(
        verbose_name='Тренированные навыки',
        choices=SkillsEnum.generate_choices(),
        min_choices=1,
        null=True,
        blank=True,
    )
    available_armor_types = MultiSelectField(
        verbose_name='Ношение доспехов',
        choices=ArmorTypeEnum.generate_choices(is_sorted=False),
        default=ArmorTypeEnum.CLOTH.name,
    )
    available_shield_types = MultiSelectField(
        verbose_name='Ношение щитов',
        choices=ShieldTypeEnum.generate_choices(),
        blank=True,
        null=True,
    )
    hit_points_per_level = models.PositiveSmallIntegerField(
        verbose_name='Хитов за уровень', default=8
    )

    def __str__(self):
        return NPCClass[self.name].value


class Armor(models.Model):
    class Meta:
        verbose_name = 'Доспех'
        verbose_name_plural = 'Доспехи'

    name = models.CharField(verbose_name='Название', max_length=20)
    type = models.CharField(
        verbose_name='Тип',
        choices=ArmorTypeEnum.generate_choices(is_sorted=False),
        max_length=ArmorTypeEnum.max_length(),
    )
    armor_class = models.SmallIntegerField(verbose_name='Класс доспеха', default=0)
    enchantment = models.SmallIntegerField(verbose_name='Улучшение', default=0)
    speed_penalty = models.SmallIntegerField(verbose_name='Штраф скорости', default=0)
    skill_penalty = models.SmallIntegerField(verbose_name='Штраф навыков', default=0)

    def __str__(self):
        return f'{self.name}, {ArmorTypeEnum[self.type].value} +{self.enchantment}'

    @property
    def is_light(self):
        return self.type in (
            ArmorTypeEnum.CLOTH.name,
            ArmorTypeEnum.LEATHER.name,
            ArmorTypeEnum.HIDE.name,
        )


class NPC(models.Model):
    class Meta:
        verbose_name = 'NPC'
        verbose_name_plural = 'NPCS'

    SEX_CHOICES = (('M', 'М'), ('F', 'Ж'), ('N', '-'))

    name = models.CharField(verbose_name='Имя', max_length=50)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    race = models.ForeignKey(
        Race,
        on_delete=models.CASCADE,
        verbose_name='Раса',
    )
    klass = models.ForeignKey(
        Class,
        on_delete=models.CASCADE,
        verbose_name='Класс',
    )

    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        verbose_name='Пол',
    )

    level = models.PositiveSmallIntegerField(
        verbose_name='Уровень',
    )

    base_strength = models.PositiveSmallIntegerField(verbose_name='Сила (базовая)')
    base_constitution = models.PositiveSmallIntegerField(
        verbose_name='Телосложение (базовое)',
    )
    base_dexterity = models.PositiveSmallIntegerField(
        verbose_name='Ловкость (базовая)',
    )
    base_intelligence = models.PositiveSmallIntegerField(
        verbose_name='Интеллект (базовый)',
    )
    base_wisdom = models.PositiveSmallIntegerField(
        verbose_name='Мудрость (базовая)',
    )
    base_charisma = models.PositiveSmallIntegerField(
        verbose_name='Харизма (базовая)',
    )

    var_bonus_attr = models.CharField(
        verbose_name='Выборочный бонус характеристики',
        max_length=AttributesEnum.max_length(),
        choices=AttributesEnum.generate_choices(is_sorted=False),
        null=True,
        blank=True,
    )

    level4_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 4 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    level8_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 8 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    level14_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 14 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    level18_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 18 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    level24_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 24 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )
    level28_bonus_attrs = MultiSelectField(
        verbose_name='Бонус характеристики на 28 уровне',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        max_choices=2,
        null=True,
        blank=True,
    )

    trained_skills = MultiSelectField(
        verbose_name='Тренированные навыки',
        choices=SkillsEnum.generate_choices(),
        min_choices=1,
        null=True,
        blank=True,
    )

    armor = models.ForeignKey(
        Armor, verbose_name='Доспехи', null=True, on_delete=models.SET_NULL
    )

    shield = models.CharField(
        verbose_name='Щит',
        max_length=5,
        choices=ShieldTypeEnum.generate_choices(),
        null=True,
        blank=True,
    )
    attack_attributes = MultiSelectField(
        verbose_name='Атакующие характеристики',
        choices=AttributesEnum.generate_choices(is_sorted=False),
        default=AttributesEnum.STRENGTH.name,
    )
    attack_bonus = models.SmallIntegerField(
        verbose_name='Бонус атаки (Оружие, инструменты + заточка', default=0
    )

    def __str__(self):
        return f'{self.name} {self.race} {self.klass} {self.level} уровня'

    @property
    def url(self):
        return reverse('npc', kwargs={'pk': self.pk})

    @property
    def half_level(self):
        return self.level // 2

    @property
    def _magic_threshold(self):
        """ Магический порог (максимальный бонус от магических предметов)"""
        return self.level // 5 + 1

    @property
    def _level_bonus(self):
        """ Условный бонус к защитам, атакам и урону для мастерских персонажей"""
        return ((self.level - 1) // 5) * 2 + 1

    @property
    def max_hit_points(self):
        return self.klass.hit_points_per_level * self.level + self.constitution

    @property
    def bloodied(self):
        return self.max_hit_points // 2

    @property
    def surge(self):
        """
        Исцеление
        """
        return self.bloodied // 2

    @property
    def surges(self):
        """Количество исцелений"""
        if self.level <= 10:
            return 1
        if self.level >= 21:
            return 3
        return 2

    @staticmethod
    def modifier(value):
        return (value - 10) // 2

    @property
    def armor_class(self):
        result = 10 + self.half_level + self._level_bonus
        if self.armor:
            if self.armor.type in self.klass.available_armor_types:
                result += self.armor.armor_class
            result += self.armor.enchantment
        if not self.armor or self.armor.is_light:
            result += max(

base/models/abstract.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.translation import gettext_lazy as _

from base.models.books import BookSource


class ClassAbstract(models.Model):
    class Meta:
        abstract = True

    weapon_categories = models.ManyToManyField(
        'base.WeaponCategory', verbose_name=_('Available weapon categories'), blank=True
    )
    weapon_types = models.ManyToManyField(
        'base.WeaponType',
        verbose_name=_('Available weapon types'),
        limit_choices_to={'primary_end__isnull': True},
        related_name='weapon_%(app_label)s_%(class)s_wielders',
        blank=True,
    )
    implement_types = models.ManyToManyField(
        'base.WeaponType',
        verbose_name=_('Available implement types'),
        limit_choices_to={'primary_end__isnull': True},
        related_name='implement_%(app_label)s_%(class)s_wielders',
        blank=True,
    )
    armor_types = models.ManyToManyField(
        'base.BaseArmorType',
        verbose_name=_('Available armor types'),
        blank=True,
    )
    shields = models.ManyToManyField(
        'base.ShieldType',
        verbose_name=_('Available shields'),
        blank=True,
    )
    book_source = models.ForeignKey(
        BookSource,
        verbose_name=_('Source'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )


class ConstraintAbstract(models.Model):
    class Meta:
        abstract = True

    constraints = GenericRelation("base.Constraint")

    @classmethod
    def get_ids_for_npc(cls, npc, initial_query=None):
        ids = set()
        if initial_query:
            queryset = cls.objects.filter(initial_query)
        else:
            queryset = cls.objects.all()
        for item in queryset:
            constraints_queryset = item.constraints.all()
            if not constraints_queryset:
                ids.add(item.id)
                continue
            for constraint in constraints_queryset:
                fits = True
                for condition in constraint.conditions.all():
                    if not condition.fits(npc):
                        fits = False
                        break
                for condition in constraint.scalar_conditions.all():
                    if not condition.fits(npc):
                        fits = False
                        break
                for condition in constraint.availability_conditions.all():
                    if not condition.fits(npc):
                        fits = False
                        break
                if fits:
                    ids.add(item.id)
                    break
        return ids

base/models/books.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Book(models.Model):
    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')
        ordering = ('name',)

    name = models.CharField(verbose_name=_('Name'), max_length=100)
    code = models.CharField(verbose_name=_('Code'), max_length=10, unique=True)

    def __str__(self):
        return self.name


class BookSource(models.Model):
    class Meta:
        verbose_name = _('Book source')
        verbose_name_plural = _('Book sources')
        unique_together = ('book', 'book_number', 'page_number', 'is_english')
        ordering = ('is_english', 'book', 'book_number', 'page_number')

    book = models.ForeignKey(Book, verbose_name=_('Book'), on_delete=models.CASCADE)
    book_number = models.PositiveSmallIntegerField(
        verbose_name=_('Book number'), default=1
    )
    page_number = models.PositiveSmallIntegerField(verbose_name=_('Page number'))
    is_english = models.BooleanField(verbose_name=_('Is English?'), default=False)

    def __str__(self):
        return (
            f'{self.book} {self.book_number},'
            f' {self.page_number} стр.'
            f'{self.is_english * " (англ.)"}'
        )

base/models/experience.py
from typing import Protocol

from django.db import models
from django.utils.translation import gettext_lazy as _

EXPERIENCE_BY_LEVEL = [
    0,
    1000,
    2250,
    3750,
    5500,
    7500,
    10000,
    13000,
    16500,
    20500,
    26000,
    32000,
    39000,
    47000,
    57000,
    69000,
    83000,
    99000,
    119000,
    143000,
    175000,
    210000,
    255000,
    310000,
    375000,
    450000,
    550000,
    675000,
    825000,
    1000000,
]


class NPCProtocol(Protocol):
    level: int
    experience: int


class NPCExperienceAbstract(models.Model):
    class Meta:
        abstract = True

    experience = models.IntegerField(verbose_name=_('Experience'), default=0)

    @staticmethod
    def level_by_experience(experience) -> int:
        level = 1
        for level, exp in enumerate(EXPERIENCE_BY_LEVEL, start=1):
            if experience == exp:
                return level
            if experience < exp:
                return level - 1
        return level

    @staticmethod
    def experience_by_level(level: int) -> int:
        return EXPERIENCE_BY_LEVEL[level - 1]

base/forms.py
from django import forms

from base.models.encounters import EncounterParticipants


class EncounterChangeInitiativeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pk = kwargs.pop('pk')
        super().__init__(*args, **kwargs)
        self.fields['participant'] = forms.ModelChoiceField(
            queryset=EncounterParticipants.objects.filter(encounter__id=pk).ordered(),
            label='Участник',
            required=True,
        )
        self.fields['move_after'] = forms.ModelChoiceField(
            queryset=EncounterParticipants.objects.filter(encounter__id=pk).ordered(),
            label='Переместить после',
            required=True,
        )

templates/base/encounter_detail.html
<!DOCTYPE html>
<html lang="en">
<style>
@media print {
.pagebreak { page-break-before: always; } /* page-break-after works, as well */
.pagenotbreak {page-break-inside: avoid}
.noprint {
    display: none !important;
}

/* Optional: Adjust column widths for print */
.print-adjust {
    width: 70% !important;  /* Expand remaining columns */
}
}
.attr-header {
    background-color: lightgray; -webkit-print-color-adjust: exact;
}
.border {
    border: 2px solid black;
    border-collapse: collapse
}
.current_turn {
    background-color: green
}
.inactive-name {
    text-decoration: line-through;
}
</style>
<head>
    <meta charset="UTF-8">
    <title>{{ object.short_description }}</title>
</head>
<body>
<div class="pagenotbreak" style="width: 1000px; font-size: large">
    <div class="noprint">
        <span>Раунд №{{object.round_number}}</span>
        <form method="post" id="round_form">
            {% csrf_token %}
            <input type="submit" id="previous_turn" name="previous_turn" value="Предыдущий ход">
            <input type="submit" id="next_turn" name="next_turn" value="Следуюший ход"><br>
        </form>
    </div>
<table class="border" style="width: 1000px; font-size: large">
    <colgroup>
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 20%;">
       <col span="1" style="width: 55%;" class="print-adjust">
       <col span="1" style="width: 5%;">
       <col span="1" style="width: 5%;" class="noprint">
       <col span="1" style="width: 10%;" class="noprint">
    </colgroup>
    <tr class="border">
    <th class="border">№</th>
    <th class="border">Имя</th>
    <th class="border">Статусы</th>
    <th class="border"></th>
    <th class="border noprint"></th>
    <th class="border noprint">Изменение инициативы</th>
  </tr>
{% for combatant in object.participants.ordered %}
    <tr class="border {% if object.turn_number_in_round == forloop.counter %}current_turn{% endif %}">
        <td class="border"><span><b>{{ forloop.counter }}</b></span></td>
        <td class="border">
            <span>
                <b class="{% if not combatant.is_active %}inactive-name{% endif %}">{{ combatant.full_name }}</b>
            </span><br>
            {% if combatant.display_defences %}
            <span style="font-size: small"><b>КД</b>: {{combatant.ac}}, <b>Ст</b>: {{combatant.fortitude}}, <b>Р</b>: {{combatant.reflex}}, <b>В</b>: {{combatant.will}} </span>
            {% endif %}
        </td>
        <td>
            <textarea name="status{{ forloop.counter }}" form="round_form" style="width: 98%">{{ combatant.status }}</textarea>
        </td>
        <td class="border"><span style="float: right">{{ combatant.initiative|floatformat:"0" }} </span></td>
        <td class="border noprint">
            {% if combatant.is_active %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="participant_id" value="{{ combatant.id }}">
                <input type="submit" name="kill_participant" value="Убить">
            </form>
            {% else %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="participant_id" value="{{ combatant.id }}">
                <input type="submit" name="unkill_participant" value="Вернуть">
            </form>
            {% endif %}
        </td>
        <td class="border noprint">
            {% if combatant.is_active %}
            <form method="post" style="display: flex; gap: 4px">
                {% csrf_token %}
                <input type="hidden" name="participant_id" value="{{ combatant.id }}">
                <select name="move_after_id" style="flex: 1">
                    <option value="">Переместить после...</option>
                    {% for target in object.participants.ordered %}
                        {% if target.id != combatant.id %}
                        <option value="{{ target.id }}">{{ target.full_name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <input type="submit" name="move_after" value="→" title="Переместить после выбранного">
            </form>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
</div>
<br>
<div class="noprint">
    <form method="post">
        {% csrf_token %}
        <input type="submit" id="roll_button" value="Бросок инициативы"><br>
    </form>
</div>
</body>
</html>

templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ДНД помощник</title>
</head>
<body>
    <div align="center">
        <h1>
        <a href="{% url 'admin:index' %}">Админка</a><br/>
        {% for link in links %}
            <a href="{{ link.1 }}">{{ link.0 }}</a><br/>
        {% endfor %}
        </h1>
    </div>
</body>
</html>

templates/base/npc_base.html
<!DOCTYPE html>
<html lang="en">
<style>
@media print {
.pagebreak { page-break-before: always; }
.pagenotbreak { page-break-inside: avoid; }
}
.npc-line { width: 100%; clear: both; }
.npc-header { background-color: black; color: white; -webkit-print-color-adjust: exact; }
.attr-header { background-color: lightgray; -webkit-print-color-adjust: exact; }
.passive { background-color: lightgray; -webkit-print-color-adjust: exact; }
.at_will { background-color: green; color: white; -webkit-print-color-adjust: exact; }
.encounter { background-color: red; color: white; -webkit-print-color-adjust: exact; }
.daily { background-color: black; color: white; -webkit-print-color-adjust: exact; }
</style>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ object.name }} (NPC){% endblock %}</title>
</head>
<body>
<div class="pagenotbreak" style="width: 800px; font-size: large">
    <div class="npc-line">
        <div class="npc-header" style="float: left; width: 50%">
            <span><b>{{ object.name }} ({{ object.get_sex_display }})</b></span>
        </div>
        <div class="npc-header" style="float: right; width: 50%">
            <span style="float: right">{{ object.race }} {{ object.klass }} {{ object.level }} уровня</span>
        </div>
        {% if not object.is_bonus_applied %}
        <div class="npc-line">
            <span>Опыт: {{ object.experience }}; Черты: {{ object.feats_count }}/{{ object.max_feats_number }}</span>
        </div>
        {% endif %}
    </div>
    <div class="npc-line">
        <div><span>Хиты {{ object.max_hit_points }}; Ранен {{ object.bloodied }}; Исцеление {{ object.surge }}; Исцелений {{ object.surges }}</span></div>
        <div><span>КД {{ object.armor_class }}; Стойкость {{ object.fortitude }}; Реакция {{ object.reflex }}; Воля {{ object.will }}</span></div>
    </div>
    <div class="npc-line">
        <div><span>Инициатива +{{ object.initiative }}; Внимательность +{{ object.perception }}; {{ object.race.get_vision_display }} зрение</span></div>
        <div><span>Скорость {{ object.speed }}</span></div>
    </div>

    {% block feats_section %}{% endblock %}
    {% block powers_section %}{% endblock %}

    <div class="npc-line attr-header"><span><b>Навыки:</b> {{ object.skills_text|join:"; " }}</span></div>
    <div class="npc-line attr-header"><span><b>Примечания:</b></span></div>
    <div class="npc-line"><span>{{ object.description|linebreaksbr }}</span></div>
    <div class="npc-line">
        <table style="width: 100%">
            <tr>
                <td style="width: 33%">{{ object.abilities_texts.0 }}</td>
                <td style="width: 33%">{{ object.abilities_texts.2 }}</td>
                <td style="width: 33%">{{ object.abilities_texts.4 }}</td>
            </tr>
            <tr>
                <td style="width: 33%">{{ object.abilities_texts.1 }}</td>
                <td style="width: 33%">{{ object.abilities_texts.3 }}</td>
                <td style="width: 33%">{{ object.abilities_texts.5 }}</td>
            </tr>
        </table>
    </div>
    <div class="npc-line attr-header"><b>Снаряжение:</b> {{ object.inventory_text|join:"; " }}</div>
    <br><hr
></div>
</body>
</html>

templates/base/npc_detail.html
{% extends "base/npc_base.html" %}

{% block feats_section %}
    {% for feat in object.feats_calculated %}
    <div class="npc-line passive" title="{{ feat.description }}">
        <span><b>{{ feat.name }} ({{ feat.category }})</b></span>
    </div>
    {% endfor %}
{% endblock %}
{% block powers_section %}
    {% for power in object.powers_calculated %}
    <div class="npc-line {{ power.frequency_css_class }}" {% if power.description %}title="{{ power.description }}"{% endif %}>
        {% if power.id %}<a href="{% url 'npc_power' pk=object.pk power_pk=power.id %}" style="text-decoration:none; color:inherit">{% endif %}
        <span><b>{{ power.name }} ({{ power.category }})</b> {{ power.keywords }}</span>
        {% if power.id %}</a>{% endif %}
    </div>
    {% for property in power.properties %}
    <div><i>{{ property.title }}</i>: {{ property.description|linebreaksbr }}</div>
<!--    <div>{{property.debug}}</div>-->
    {% endfor %}
    {% endfor %}
{% endblock %}

templates/base/npc_list.html
<h1>NPCS</h1>
<ul>
{% for npc in object_list %}
    <li><a href="{{ npc.get_absolute_url }}">{{ npc }}</a></li>
{% empty %}
    <li>No npcs yet.</li>
{% endfor %}
</ul>

templates/base/npc_power_detail.html
{% extends "base/npc_base.html" %}

{% block powers_section %}
    {% for power in powers %}
    <div class="npc-line {{ power.frequency_css_class }}">
        <span><b>{{ power.name }} ({{ power.category }})</b> {{ power.keywords }}<br></span>
        {% if power.description %}<span><i>{{ power.description }}</i></span>{% endif %}
    </div>
    {% for property in power.properties %}
    <div><i>{{ property.title }}</i>: {{ property.description|linebreaksbr }}</div>
    {% endfor %}
    {% endfor %}
{% endblock %}

templates/base/pcparty_detail.html
<!DOCTYPE html>
<html lang="en">
<style>
.border {
    border: 2px solid black;
    border-collapse: collapse
}
.center {
    text-align: center
}
</style>
<head>
    <meta charset="UTF-8">
    <title>{{ object }}</title>
</head>
<body>
<div class="pagenotbreak" style="width: 1000px; font-size: large">
<table class="border" style="width: 1000px; font-size: large">
    <colgroup>
       <col span="1" style="width: 40%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 10%;">
    </colgroup>
    <tr class="border">
      <th class="border">Имя</th>
      <th class="border">КД</th>
      <th class="border">Стойкость</th>
      <th class="border">Реакция</th>
      <th class="border">Воля</th>
      <th class="border">Пассивная внимательность</th>
      <th class="border">Пассивная проницательность</th>
    </tr>
{% for member in object.members.all %}
    <tr class="border">
      <td class="border center"><span><b>{{ member.name }}</b></span></td>
      <td class="border center"><span><b>{{ member.armor_class }}</b></span></td>
      <td class="border center"><span><b>{{ member.fortitude }}</b></span></td>
      <td class="border center"><span><b>{{ member.reflex }}</b></span></td>
      <td class="border center"><span><b>{{ member.will }}</b></span></td>
      <td class="border center"><span><b>{{ member.passive_perception }}</b></span></td>
      <td class="border center"><span><b>{{ member.passive_insight }}</b></span></td>
    </tr>
{% endfor %}
</table>
</div>
</body>
</html>